### ISSUE TITLE
uninitialized constant Gmail (NameError)

### ISSUE THREAD

**Issue by juhat** [dcparker/ruby-gmail#15]
I just installed ruby-gmail via gem. I created a sample program, but I cant make it work. It just hangs up, when Gmal class is used. "uninitialized constant Gmail (NameError)"

The code is:
require 'rubygems'
require 'gmail'
gmail = Gmail.new(...etc

Platform:
Ubuntu, REE 1.8.6, ruby-gmail 0.0.8

**Comment by isakshamgupta** [comment]
need help regarding the same
