### ISSUE TITLE
The Next Version

### ISSUE THREAD

**Issue by myobie** [dcparker/ruby-gmail#58]
Shortly, I want to begin the next version of ruby-gmail.

This gem should live up to this description:

> A Rubyesque interface to Gmail, with all the tools you'll need. Search, read and send multipart emails; archive, mark as read/unread, delete emails; and manage labels.

To get there I think these steps need to be taken:
- [ ] convert to use the mail gem behind the scenes
- [ ] sketch a newer gmail dsl
- [ ] spec out high level stuff
- [ ] figure out and full spec out labels

These are very _generic_ todos, but I think they are the path forward. Labels are super important. Also being able to peak and not mark as read will be huge.

If anyone is interested in helping or has comments on the direction please feel free to comment here.

The work for 2.0 will take place on [my fork](https://github.com/myobie/ruby-gmail/).

**Comment by johnnyshields** [comment]
@myobie I'm a user/maintaner of [gmailgem/gmail](https://github.com/gmailgem/gmail) (formerly [nu7hatch/gmail](https://github.com/nu7hatch/gmail) which was originally forked from this repo. We'd be very keen to join efforts on the gmailgem fork as our goals essentially the same, i.e. more usable API, better testing, etc.

**Comment by myobie** [comment]
@johnnyshields awesome. I'd like to get some tests started so we can all get it going soon. I've added you as a collaborator.

**Comment by myobie** [comment]
@gabrielengel regarding your gist I do have this feedback:

I don't think we need to manage any state, instead we can just return objects from every call. An example of what this would look like from your gist would be:

```ruby
Gmail.new(username, password) do |gmail|
  gmail.in('inbox').count # => 100

  gmail.search('is:unread').count # => 60

  gmail.search('is:read').count # => 40

  gmail.search('before:2010-02-20 after:2010-03-20')
  gmail.search('on:2010-04-15')
  gmail.search('from:myfriend@gmail.com')
  gmail.search('to:myfriend@gmail.com')
  gmail.search('is:read from:myboss@gmail.com "you are a great employee"')

  gmail.peek do |peek|
    peek.in('Urgent').count
  end
end
```

**Comment by johnnyshields** [comment]
@myobie, I've added you to the gmailgem organization. Come over to our side--we have an awesome team and a reliable approach to test the gem on Travis CI with specs now green. Your suggested improvements are most welcome.

**Comment by simo2409** [comment]
I think it would be useful in the new version to abandon username/password auth and using Gmail's API.
Until you use ruby (and ruby-gmail) on your desktop it's the same but using them on a webapp it drives to 
````
Please log in via your web browser: http://support.google.com/mail/accounts/bin/answer.py?answer=78754 (Failure)
````

**Comment by myobie** [comment]
I'm closing this since it's so old.
