### ISSUE TITLE
Gem is unusable, "Please log in via your web browser"

### ISSUE THREAD

**Issue by ilovemysillybanana** [dcparker/ruby-gmail#83]
/home/jose/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/imap.rb:1171:in `get_tagged_response':  Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure) (Net::IMAP::NoResponseError)
	from /home/jose/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/imap.rb:1225:in `block in send_command'
	from /home/jose/.rbenv/versions/2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /home/jose/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/imap.rb:1207:in `send_command'
	from /home/jose/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/imap.rb:435:in `login'
	from /home/jose/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-gmail-0.3.1/lib/gmail.rb:114:in `login'
	from /home/jose/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruby-gmail-0.3.1/lib/gmail.rb:23:in `initialize'
	from CollegeEmailSpammer.rb:18:in `new'
	from CollegeEmailSpammer.rb:18:in `gmailer'
	from CollegeEmailSpammer.rb:37:in `<main>'

**Comment by tobyhinloopen** [comment]
Same here :(

**Comment by ilovemysillybanana** [comment]
I'm not sure why this one doesn't or didn't work, I ended up using a different gem but it seems to use either of these gems with just the basic set up you'll have to change the security settings on your account.

You might wanna try it after doing that:
https://support.google.com/accounts/answer/6010255?hl=en

**Comment by tobyhinloopen** [comment]
That worked for me as well. :) Thanks

**Comment by zipizap** [comment]
Could not get it to work either: 
```
imap.rb:1156:in `get_tagged_response':  Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure) (Net::IMAP::NoResponseError)
```


> You might wanna try it after doing that:
>https://support.google.com/accounts/answer/6010255?hl=en

Tried it but unfurtonately it was not enough, the error persists...

**Comment by petethepig** [comment]
Same here

**Comment by petethepig** [comment]
Sorry, it was enabled for a different account

**Comment by trejkaz** [comment]
Mine was already enabled but I'm getting the error. I also tried visiting https://www.google.com/accounts/DisplayUnlockCaptcha and have confirmed it over and over, and it doesn't do anything. :(
